# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-02-14 16:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Projeto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_projeto', models.CharField(max_length=32, verbose_name='Nome do Projeto')),
                ('sg_projeto', models.CharField(max_length=32, unique=True, verbose_name='Sigla')),
                ('dt_inicio', models.DateField(verbose_name='Data Início')),
                ('dt_fim', models.DateField(verbose_name='Data Fim')),
                ('du_duracao_meses', models.IntegerField(verbose_name='Quantidade de meses de duração')),
                ('identificao_objeto', models.TextField(max_length=2048, verbose_name='Identificação do Projeto')),
                ('justificativa', models.TextField(max_length=2048, verbose_name='Justificativa')),
                ('referencias_bibliograficas', models.TextField(max_length=2048, verbose_name='Referências Bibliográficas')),
                ('metodologia', models.TextField(max_length=1024, verbose_name='metodologia')),
                ('gestao_transferencia_tecnologia', models.TextField(max_length=1024, verbose_name='Gestão de Transferência de Tecnologia')),
                ('fk_entidade_concedente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='concedente', to='core.Entidade')),
                ('fk_entidade_proponente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proponente', to='core.Entidade')),
                ('fk_responsavel_concedente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='concedente', to='core.Responsavel')),
                ('fk_responsavel_proponente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proponente', to='core.Responsavel')),
            ],
        ),
    ]
