# Generated by Django 2.0.2 on 2018-05-01 00:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bolsista',
            name='projeto_atual',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='atuacao', to='core.Projeto'),
        ),
    ]
