# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-12 02:13
from __future__ import unicode_literals

import common.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bolsista',
            name='cpf',
            field=models.CharField(max_length=14, unique=True, validators=[common.validators.cpf], verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='bolsista',
            name='dt_nascimento',
            field=models.CharField(max_length=10, verbose_name='Data de Nascimento'),
        ),
    ]
