# Generated by Django 2.0.2 on 2018-04-30 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bolsista',
            name='tipo_conta',
            field=models.CharField(choices=[('1', 'Conta-poupança'), ('2', 'Conta-corrente')], default='1', max_length=1, verbose_name='Tipo de Conta'),
        ),
    ]
