# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-12 02:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20180112_0213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bolsista',
            name='dt_nascimento',
            field=models.DateField(verbose_name='Data de Nascimento'),
        ),
    ]
