# Generated by Django 2.0.2 on 2018-04-30 18:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20180430_1317'),
    ]

    operations = [
        migrations.AddField(
            model_name='bolsista',
            name='projeto_atual',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='core.Projeto'),
        ),
        migrations.AlterField(
            model_name='bolsista',
            name='tipo_conta',
            field=models.CharField(choices=[('1', 'Conta-poupança'), ('2', 'Conta-corrente')], default='2', max_length=1, verbose_name='Tipo de Conta'),
        ),
    ]
