# Generated by Django 2.0.2 on 2018-04-30 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20180430_1820'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projeto',
            old_name='fk_entidade_concedente',
            new_name='entidade_concedente',
        ),
        migrations.RenameField(
            model_name='projeto',
            old_name='fk_entidade_proponente',
            new_name='entidade_proponente',
        ),
        migrations.RenameField(
            model_name='projeto',
            old_name='fk_responsavel_concedente',
            new_name='responsavel_concedente',
        ),
        migrations.RenameField(
            model_name='projeto',
            old_name='fk_responsavel_proponente',
            new_name='responsavel_proponente',
        ),
        migrations.RemoveField(
            model_name='projeto',
            name='fk_bolsista',
        ),
        migrations.RemoveField(
            model_name='projeto',
            name='fk_funcao',
        ),
    ]
