# Generated by Django 2.0.2 on 2018-07-17 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20180501_2347'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjetoDenominacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=32, verbose_name='Nome do Projeto')),
                ('sigla', models.CharField(max_length=32, unique=True, verbose_name='Sigla')),
            ],
        ),
    ]
