# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-12 02:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20180112_0246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bolsista',
            name='endereco',
            field=models.CharField(max_length=128, verbose_name='Endereço'),
        ),
    ]
