# Generated by Django 2.0.2 on 2018-07-30 01:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_projetodenominacao'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projetodenominacao',
            options={'verbose_name': 'Denominação de Projeto', 'verbose_name_plural': 'Denominações de Projetos'},
        ),
    ]
