# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-12 03:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20180112_0249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bolsista',
            name='agencia',
            field=models.CharField(choices=[('001', '001 - BANCO DO BRASIL S/A'), ('002', '002 - BANCO CENTRAL DO BRASIL'), ('003', '003 - BANCO DA AMAZONIA S.A'), ('004', '004 - BANCO DO NORDESTE DO BRASIL S.A'), ('070', '070 - BANCO DE BRASILIA S.A'), ('104', '104 - CAIXA ECONOMICA FEDERAL'), ('237', '237 - BANCO BRADESCO S.A'), ('275', '275 - BANCO REAL S.A'), ('341', '341 - BANCO ITAU S.A'), ('409', '409 - UNIBANCO - UNIAO DOS BANCOS BRASILEIROS'), ('422', '422 - BANCO SAFRA S.A'), ('477', '477 - CITIBANK N.A'), ('502', '502 - BANCO SANTANDER S.A')], max_length=32, verbose_name='Agência'),
        ),
    ]
