# Generated by Django 2.0.2 on 2018-07-30 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20180730_0159'),
    ]

    operations = [
        migrations.AddField(
            model_name='bolsista',
            name='categoria',
            field=models.CharField(blank=True, max_length=100, verbose_name='Categoria'),
        ),
        migrations.AddField(
            model_name='bolsista',
            name='horas_semanais',
            field=models.CharField(blank=True, max_length=100, verbose_name='Número de Horas semanais'),
        ),
        migrations.AddField(
            model_name='bolsista',
            name='inicio_vigencia',
            field=models.CharField(blank=True, max_length=100, verbose_name='Início da Vigência'),
        ),
        migrations.AddField(
            model_name='bolsista',
            name='modalidade',
            field=models.CharField(blank=True, max_length=100, verbose_name='Modalidade'),
        ),
        migrations.AddField(
            model_name='bolsista',
            name='nivel',
            field=models.CharField(blank=True, max_length=100, verbose_name='Nível'),
        ),
        migrations.AddField(
            model_name='bolsista',
            name='periodo_total',
            field=models.CharField(blank=True, max_length=100, verbose_name='Período Total Previsto'),
        ),
        migrations.AddField(
            model_name='bolsista',
            name='termino_vigencia',
            field=models.CharField(blank=True, max_length=100, verbose_name='Término da Vigência'),
        ),
        migrations.AddField(
            model_name='bolsista',
            name='valor_mensal',
            field=models.CharField(blank=True, max_length=100, verbose_name='Valor Mensal'),
        ),
        migrations.AddField(
            model_name='bolsista',
            name='valor_total',
            field=models.CharField(blank=True, max_length=100, verbose_name='Valor Total'),
        ),
    ]
