# Generated by Django 2.0.2 on 2018-08-31 00:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20180730_1209'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjetoInteressados',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entidade_concedente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='concedente', to='core.Entidade')),
                ('entidade_proponente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proponente', to='core.Entidade')),
                ('responsavel_concedente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='concedente', to='core.Responsavel')),
                ('responsavel_proponente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proponente', to='core.Responsavel')),
            ],
            options={
                'verbose_name_plural': 'Interessados ao Projeto',
                'verbose_name': 'Interessado ao Projeto',
            },
        ),
        migrations.CreateModel(
            name='ProjetoMetas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metodologia', models.TextField(max_length=1024, verbose_name='metodologia')),
                ('gestao_transferencia_tecnologia', models.TextField(max_length=1024, verbose_name='Gestão de Transferência de Tecnologia')),
            ],
            options={
                'verbose_name_plural': 'Interessados ao Projeto',
                'verbose_name': 'Interessado ao Projeto',
            },
        ),
        migrations.RemoveField(
            model_name='projeto',
            name='entidade_concedente',
        ),
        migrations.RemoveField(
            model_name='projeto',
            name='entidade_proponente',
        ),
        migrations.RemoveField(
            model_name='projeto',
            name='no_projeto',
        ),
        migrations.RemoveField(
            model_name='projeto',
            name='responsavel_concedente',
        ),
        migrations.RemoveField(
            model_name='projeto',
            name='responsavel_proponente',
        ),
        migrations.RemoveField(
            model_name='projeto',
            name='sg_projeto',
        ),
    ]
