# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-12 03:22
from __future__ import unicode_literals

import common.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20180112_0307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bolsista',
            name='cpf',
            field=models.CharField(max_length=14, unique=True, validators=[common.validators.cpf], verbose_name='CPF'),
        ),
    ]
