# Generated by Django 2.0.2 on 2018-08-31 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20180831_0019'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projetometas',
            options={'verbose_name': 'Metodo do Projeto', 'verbose_name_plural': 'Metodos do projeto'},
        ),
        migrations.AddField(
            model_name='projetometas',
            name='atividade_vinvulada',
            field=models.TextField(default='blank', max_length=1024, verbose_name='Atividade vinculada'),
        ),
        migrations.AddField(
            model_name='projetometas',
            name='atividades_previstas',
            field=models.TextField(default='blank', max_length=1024, verbose_name='Atividades previstas'),
        ),
        migrations.AddField(
            model_name='projetometas',
            name='descricao_meta',
            field=models.TextField(default='blank', max_length=1024, verbose_name='Descrição da meta'),
        ),
        migrations.AddField(
            model_name='projetometas',
            name='meta',
            field=models.CharField(default='blank', max_length=64, verbose_name='Titulo da meta'),
        ),
        migrations.AddField(
            model_name='projetometas',
            name='meta_especifica',
            field=models.TextField(default='blank', max_length=1024, verbose_name='Meta Específica'),
        ),
        migrations.AlterField(
            model_name='projetometas',
            name='gestao_transferencia_tecnologia',
            field=models.TextField(default='blank', max_length=1024, verbose_name='Gestão de Transferência de Tecnologia'),
        ),
        migrations.AlterField(
            model_name='projetometas',
            name='metodologia',
            field=models.TextField(default='blank', max_length=1024, verbose_name='Metodologia'),
        ),
    ]
