# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-02-14 22:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20180112_0322'),
        ('core', '0002_projeto'),
    ]

    operations = [
    ]
