# Generated by Django 2.0.2 on 2018-08-31 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20180831_0043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projetometas',
            name='atividade_vinvulada',
            field=models.TextField(default='', max_length=1024, verbose_name='Atividade vinculada'),
        ),
        migrations.AlterField(
            model_name='projetometas',
            name='atividades_previstas',
            field=models.TextField(default='', max_length=1024, verbose_name='Atividades previstas'),
        ),
        migrations.AlterField(
            model_name='projetometas',
            name='descricao_meta',
            field=models.TextField(default='', max_length=1024, verbose_name='Descrição da meta'),
        ),
        migrations.AlterField(
            model_name='projetometas',
            name='gestao_transferencia_tecnologia',
            field=models.TextField(default='', max_length=1024, verbose_name='Gestão de Transferência de Tecnologia'),
        ),
        migrations.AlterField(
            model_name='projetometas',
            name='meta',
            field=models.CharField(default='', max_length=64, verbose_name='Titulo da meta'),
        ),
        migrations.AlterField(
            model_name='projetometas',
            name='meta_especifica',
            field=models.TextField(default='', max_length=1024, verbose_name='Meta Específica'),
        ),
        migrations.AlterField(
            model_name='projetometas',
            name='metodologia',
            field=models.TextField(default='', max_length=1024, verbose_name='Metodologia'),
        ),
    ]
