# Generated by Django 2.0.2 on 2018-09-05 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20180831_0044'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projeto',
            name='gestao_transferencia_tecnologia',
        ),
        migrations.RemoveField(
            model_name='projeto',
            name='identificao_objeto',
        ),
        migrations.RemoveField(
            model_name='projeto',
            name='justificativa',
        ),
        migrations.RemoveField(
            model_name='projeto',
            name='metodologia',
        ),
    ]
