# Generated by Django 2.0.2 on 2018-09-05 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_auto_20180905_0844'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjetoAnexos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.ImageField(upload_to=None, verbose_name='Anexos')),
            ],
            options={
                'verbose_name_plural': 'Anexos do projeto',
                'verbose_name': 'Anexo do Projeto',
            },
        ),
    ]
