# Generated by Django 2.0.2 on 2018-09-08 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_projetoanexos'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjetoBolsista',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_bolsista_pr', models.CharField(default='', max_length=1024, verbose_name='Nome do bolsista')),
            ],
            options={
                'verbose_name': 'Bolsista do Projeto',
                'verbose_name_plural': 'Bolsistas do Projeto',
            },
        ),
    ]
