# Generated by Django 2.0.2 on 2018-09-21 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_projetobolsista'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projetointeressados',
            name='entidade_proponente',
            field=models.CharField(default='1', max_length=1, verbose_name='Entidade'),
        ),
    ]
