# Generated by Django 2.0.2 on 2018-09-21 21:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_auto_20180921_2100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projetobolsista',
            name='nome_bolsista_pr',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participante', to='core.Bolsista'),
        ),
    ]
