# Generated by Django 2.0.2 on 2018-09-24 21:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_auto_20180921_2148'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projetobolsista',
            name='nome_bolsista_pr',
        ),
        migrations.DeleteModel(
            name='ProjetoBolsista',
        ),
    ]
