# Generated by Django 2.0.2 on 2018-09-24 21:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_auto_20180924_2132'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Projeto',
        ),
    ]
