# Generated by Django 2.0.2 on 2018-10-16 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_delete_projeto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bolsista',
            name='horas_semanais',
        ),
        migrations.RemoveField(
            model_name='bolsista',
            name='inicio_vigencia',
        ),
        migrations.RemoveField(
            model_name='bolsista',
            name='periodo_total',
        ),
        migrations.RemoveField(
            model_name='bolsista',
            name='termino_vigencia',
        ),
        migrations.RemoveField(
            model_name='bolsista',
            name='valor_mensal',
        ),
        migrations.RemoveField(
            model_name='bolsista',
            name='valor_total',
        ),
    ]
