# Generated by Django 2.0.2 on 2018-10-16 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_auto_20181016_2010'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bolsista',
            name='funcao',
        ),
        migrations.AddField(
            model_name='bolsista',
            name='horas_semanais',
            field=models.CharField(blank=True, max_length=100, verbose_name='Número de Horas semanais'),
        ),
        migrations.AddField(
            model_name='bolsista',
            name='inicio_vigencia',
            field=models.CharField(blank=True, max_length=100, verbose_name='Início da Vigência'),
        ),
        migrations.AddField(
            model_name='bolsista',
            name='periodo_total',
            field=models.CharField(blank=True, max_length=100, verbose_name='Período Total Previsto'),
        ),
        migrations.AddField(
            model_name='bolsista',
            name='termino_vigencia',
            field=models.CharField(blank=True, max_length=100, verbose_name='Término da Vigência'),
        ),
        migrations.AddField(
            model_name='bolsista',
            name='valor_mensal',
            field=models.CharField(blank=True, max_length=100, verbose_name='Valor Mensal'),
        ),
        migrations.AddField(
            model_name='bolsista',
            name='valor_total',
            field=models.CharField(blank=True, max_length=100, verbose_name='Valor Total'),
        ),
    ]
