# Generated by Django 2.0.2 on 2018-10-16 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_auto_20181016_2012'),
    ]

    operations = [
        migrations.AddField(
            model_name='bolsista',
            name='funcao',
            field=models.CharField(choices=[('1', '5'), ('2', '4'), ('2', '3'), ('4', '2'), ('5', '1')], default='1', max_length=1, verbose_name='Funcao'),
        ),
    ]
