# Generated by Django 2.0.2 on 2018-10-16 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_bolsista_funcao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bolsista',
            name='funcao',
        ),
    ]
