# Generated by Django 2.0.2 on 2018-10-17 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_remove_bolsista_funcao'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProjetoAnexos',
        ),
        migrations.RemoveField(
            model_name='projetointeressados',
            name='entidade_concedente',
        ),
        migrations.RemoveField(
            model_name='projetointeressados',
            name='entidade_proponente',
        ),
        migrations.RemoveField(
            model_name='projetointeressados',
            name='responsavel_concedente',
        ),
        migrations.RemoveField(
            model_name='projetointeressados',
            name='responsavel_proponente',
        ),
        migrations.DeleteModel(
            name='ProjetoMetas',
        ),
        migrations.AlterModelOptions(
            name='bolsista',
            options={'verbose_name': 'Bolsista', 'verbose_name_plural': 'Bolsistas'},
        ),
        migrations.AlterModelOptions(
            name='projetodenominacao',
            options={'verbose_name': 'Anexo do Projeto', 'verbose_name_plural': 'Anexos do projeto'},
        ),
        migrations.AddField(
            model_name='projetodenominacao',
            name='atividade_vinvulada',
            field=models.TextField(default='', max_length=1024, verbose_name='Atividade vinculada'),
        ),
        migrations.AddField(
            model_name='projetodenominacao',
            name='atividades_previstas',
            field=models.TextField(default='', max_length=1024, verbose_name='Atividades previstas'),
        ),
        migrations.AddField(
            model_name='projetodenominacao',
            name='descricao_meta',
            field=models.TextField(default='', max_length=1024, verbose_name='Descrição da meta'),
        ),
        migrations.AddField(
            model_name='projetodenominacao',
            name='entidade_concedente',
            field=models.ManyToManyField(related_name='concedente', to='core.Entidade'),
        ),
        migrations.AddField(
            model_name='projetodenominacao',
            name='entidade_proponente',
            field=models.ManyToManyField(related_name='proponente', to='core.Entidade'),
        ),
        migrations.AddField(
            model_name='projetodenominacao',
            name='file',
            field=models.ImageField(default=0, upload_to=None, verbose_name='Anexos'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='projetodenominacao',
            name='gestao_transferencia_tecnologia',
            field=models.TextField(default='', max_length=1024, verbose_name='Gestão de Transferência de Tecnologia'),
        ),
        migrations.AddField(
            model_name='projetodenominacao',
            name='meta',
            field=models.CharField(default='', max_length=64, verbose_name='Titulo da meta'),
        ),
        migrations.AddField(
            model_name='projetodenominacao',
            name='meta_especifica',
            field=models.TextField(default='', max_length=1024, verbose_name='Meta Específica'),
        ),
        migrations.AddField(
            model_name='projetodenominacao',
            name='metodologia',
            field=models.TextField(default='', max_length=1024, verbose_name='Metodologia'),
        ),
        migrations.AddField(
            model_name='projetodenominacao',
            name='responsavel_concedente',
            field=models.ManyToManyField(related_name='concedente', to='core.Responsavel'),
        ),
        migrations.AddField(
            model_name='projetodenominacao',
            name='responsavel_proponente',
            field=models.ManyToManyField(related_name='proponente', to='core.Responsavel'),
        ),
        migrations.DeleteModel(
            name='ProjetoInteressados',
        ),
    ]
