# Generated by Django 2.0.2 on 2018-10-17 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_auto_20181017_0158'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projetodenominacao',
            options={'verbose_name': 'Projeto', 'verbose_name_plural': 'Projetos'},
        ),
        migrations.AddField(
            model_name='projetodenominacao',
            name='participante',
            field=models.ManyToManyField(to='core.Bolsista'),
        ),
    ]
