# Generated by Django 2.0.2 on 2018-10-17 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_auto_20181017_0406'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projetodenominacao',
            name='file',
            field=models.FileField(upload_to=None, verbose_name='Anexos'),
        ),
    ]
