# Generated by Django 2.0.2 on 2018-10-19 03:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_auto_20181017_0406'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bolsista',
            name='projeto_atual',
        ),
    ]
