# Generated by Django 2.0.2 on 2018-10-19 04:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_remove_bolsista_projeto_atual'),
    ]

    operations = [
        migrations.AddField(
            model_name='bolsista',
            name='projeto_atual',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='atuacao', to='core.ProjetoDenominacao'),
        ),
        migrations.AddField(
            model_name='projetodenominacao',
            name='resumo',
            field=models.TextField(default='', max_length=1024, verbose_name='Resumo do projeto'),
        ),
    ]
