# Generated by Django 2.0.2 on 2018-10-17 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_auto_20181017_1134'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projetodenominacao',
            name='file',
        ),
    ]
