# Generated by Django 2.0.2 on 2018-10-19 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_auto_20181019_0415'),
    ]

    operations = [
        migrations.AddField(
            model_name='projetodenominacao',
            name='atividade_geral',
            field=models.CharField(choices=[('1', 'INSERIR'), ('2', 'INSERIR'), ('2', 'INSERIR'), ('4', 'INSERIR'), ('5', 'INSERIR')], default='', max_length=1, verbose_name='Atividade'),
        ),
        migrations.AddField(
            model_name='projetodenominacao',
            name='meta_geral',
            field=models.CharField(choices=[('1', 'Controle de Andamento do Projeto'), ('2', 'Definição e Operacionalização da Arquitetura de Integração e Interoperação'), ('2', 'Modelo de Arquitetura e Medidas de Segutança dos Sistemas de Informações'), ('4', 'Acompanhamento da Operalização dos Processos de Gorvernança e TI na DPU')], default='', max_length=1, verbose_name='Meta'),
        ),
    ]
