# Generated by Django 2.0.2 on 2018-10-18 16:27

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_remove_projetodenominacao_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='projetodenominacao',
            name='file',
            field=models.ImageField(default=django.utils.timezone.now, upload_to=None, verbose_name='Anexos'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bolsista',
            name='projeto_atual',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='atuacao', to='core.ProjetoDenominacao'),
        ),
        migrations.AlterField(
            model_name='projetodenominacao',
            name='participante',
            field=models.ManyToManyField(to='core.Bolsista'),
        ),
    ]
