# Generated by Django 2.0.2 on 2018-10-25 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_auto_20181019_0428'),
        ('core', '0032_auto_20181018_1627'),
    ]

    operations = [
    ]
