# Generated by Django 2.0.2 on 2018-10-25 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_merge_20181025_1138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bolsista',
            name='cep',
            field=models.CharField(max_length=32, verbose_name='CEP'),
        ),
        migrations.AlterField(
            model_name='bolsista',
            name='no_bolsista',
            field=models.CharField(max_length=32, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='bolsista',
            name='rg',
            field=models.CharField(max_length=32, verbose_name='RG'),
        ),
        migrations.AlterField(
            model_name='entidade',
            name='co_esfera',
            field=models.CharField(max_length=32, verbose_name='Esfera'),
        ),
        migrations.AlterField(
            model_name='entidade',
            name='de_endereco',
            field=models.CharField(max_length=128, verbose_name='Endereço'),
        ),
    ]
