# Generated by Django 2.0.2 on 2018-10-25 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_auto_20181025_1459'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProjetoDenominacao',
            new_name='Projeto',
        ),
    ]
