# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-30 02:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administracao', '0002_auto_20171021_1835'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cargo',
            name='nu_cargo',
        ),
        migrations.RemoveField(
            model_name='entidade',
            name='nu_entidade',
        ),
        migrations.RemoveField(
            model_name='responsavel',
            name='nu_responsavel',
        ),
    ]
