# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-30 05:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracao', '0003_auto_20171030_0215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entidade',
            name='cep',
            field=models.IntegerField(verbose_name='CEP'),
        ),
        migrations.AlterField(
            model_name='entidade',
            name='cnpj',
            field=models.IntegerField(unique=True, verbose_name='CNPJ'),
        ),
        migrations.AlterField(
            model_name='entidade',
            name='co_entidade',
            field=models.CharField(max_length=32, unique=True, verbose_name='Código'),
        ),
        migrations.AlterField(
            model_name='entidade',
            name='co_esfera',
            field=models.CharField(max_length=32, unique=True, verbose_name='Esfera'),
        ),
        migrations.AlterField(
            model_name='entidade',
            name='de_endereco',
            field=models.CharField(max_length=128, unique=True, verbose_name='Endereço'),
        ),
        migrations.AlterField(
            model_name='entidade',
            name='ic_ativo',
            field=models.BooleanField(verbose_name='Ativo'),
        ),
        migrations.AlterField(
            model_name='entidade',
            name='no_entidade',
            field=models.CharField(max_length=32, unique=True, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='entidade',
            name='nu_municipio',
            field=models.IntegerField(verbose_name='Número do municipio'),
        ),
        migrations.AlterField(
            model_name='entidade',
            name='sg_entidade',
            field=models.CharField(max_length=32, unique=True, verbose_name='Sigla'),
        ),
        migrations.AlterField(
            model_name='entidade',
            name='telefone',
            field=models.IntegerField(verbose_name='Telefone'),
        ),
    ]
