# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-30 05:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracao', '0004_auto_20171030_0502'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cargo',
            name='ic_ativo',
            field=models.BooleanField(verbose_name='Ativo'),
        ),
        migrations.AlterField(
            model_name='cargo',
            name='no_cargo',
            field=models.CharField(max_length=32, unique=True, verbose_name='Nome'),
        ),
    ]
