# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-01 03:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracao', '0005_auto_20171030_0502'),
    ]

    operations = [
        migrations.CreateModel(
            name='Funcao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_funcao', models.CharField(max_length=6, unique=True, verbose_name='Nome')),
                ('ic_ativo', models.BooleanField(verbose_name='Ativo')),
            ],
        ),
        migrations.AlterField(
            model_name='cargo',
            name='no_cargo',
            field=models.CharField(max_length=6, unique=True, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='responsavel',
            name='co_matricula',
            field=models.CharField(max_length=32, unique=True, verbose_name='Matrícula'),
        ),
        migrations.AlterField(
            model_name='responsavel',
            name='cpf',
            field=models.IntegerField(verbose_name='CPF'),
        ),
        migrations.AlterField(
            model_name='responsavel',
            name='ic_ativo',
            field=models.BooleanField(verbose_name='Ativo'),
        ),
        migrations.AlterField(
            model_name='responsavel',
            name='no_responsavel',
            field=models.CharField(max_length=32, unique=True, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='responsavel',
            name='telefone',
            field=models.IntegerField(verbose_name='Telefone'),
        ),
    ]
